import React, { useState } from 'react';
import { generateSafetyAlert } from '../services/gemini';
import { Send, FileText, AlertOctagon, AlertTriangle, XCircle, Share2, Check } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';
import { jsPDF } from 'jspdf';

const Alerts: React.FC = () => {
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    location: 'Sundarbans, Bangladesh',
    transportType: 'Tourist Boat'
  });
  const [alertResult, setAlertResult] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [errorCode, setErrorCode] = useState('');
  const [copyFeedback, setCopyFeedback] = useState(false);
  const { language, t } = useLanguage();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setAlertResult('');
    setError('');
    setErrorCode('');
    setCopyFeedback(false);
    
    try {
      const result = await generateSafetyAlert(formData.name, formData.location, formData.transportType, language);
      setAlertResult(result);
    } catch (error: any) {
      console.error(error);
      setError(error.message || "Error generating alert. Please check your connection and try again.");
      setErrorCode(error.code || '');
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleShare = async () => {
    if (!alertResult) return;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'AI Haor Guardian Safety Alert',
          text: alertResult,
        });
      } catch (err) {
        console.error('Share failed:', err);
      }
    } else {
      try {
        await navigator.clipboard.writeText(alertResult);
        setCopyFeedback(true);
        setTimeout(() => setCopyFeedback(false), 2000);
      } catch (err) {
        console.error('Copy failed:', err);
      }
    }
  };

  const handleSavePDF = () => {
    if (!alertResult) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;

    // Header
    doc.setFontSize(22);
    doc.setTextColor(14, 165, 233); // Primary color #0ea5e9
    doc.text("Global Wetland Guardian", margin, 20);
    
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42); // Slate 900
    doc.text("Safety Advisory", margin, 30);

    // Separator line
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, 35, pageWidth - margin, 35);

    // Metadata
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    
    const dateStr = new Date().toLocaleDateString();
    doc.text(`${t('alert.form.name')}: ${formData.name}`, margin, 45);
    doc.text(`${t('alert.form.location')}: ${formData.location}`, margin, 52);
    doc.text(`${t('alert.form.transport')}: ${formData.transportType}`, margin, 59);
    doc.text(`Date: ${dateStr}`, margin, 66);

    // Content Title
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(t('alert.result.title'), margin, 80);

    // Content Body
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    
    // Split text to fit width
    const splitText = doc.splitTextToSize(alertResult, maxLineWidth);
    doc.text(splitText, margin, 90);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    const footerText = "Generated by Global Wetland Guardian - Stay Safe";
    doc.text(footerText, margin, doc.internal.pageSize.getHeight() - 10);

    doc.save(`wetland_safety_alert_${Date.now()}.pdf`);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-slate-900 dark:text-white">{t('alert.title')}</h2>
          <p className="mt-2 text-slate-600 dark:text-slate-400">{t('alert.subtitle')}</p>
        </div>

        <div className="bg-white dark:bg-slate-900 shadow-xl rounded-2xl overflow-hidden border border-slate-200 dark:border-slate-800">
          <div className="p-8">
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">{t('alert.form.name')}</label>
                  <input
                    type="text"
                    name="name"
                    required
                    value={formData.name}
                    onChange={handleChange}
                    className="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white shadow-sm focus:border-primary focus:ring-primary py-2.5 px-3 border"
                    placeholder="name"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">{t('alert.form.phone')}</label>
                  <input
                    type="tel"
                    name="phone"
                    value={formData.phone}
                    onChange={handleChange}
                    className="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white shadow-sm focus:border-primary focus:ring-primary py-2.5 px-3 border"
                    placeholder=""
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">{t('alert.form.location')}</label>
                  <input
                    type="text"
                    name="location"
                    value={formData.location}
                    onChange={handleChange}
                    className="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white shadow-sm focus:border-primary focus:ring-primary py-2.5 px-3 border"
                    placeholder="e.g. Sundarbans, Everglades, Mekong Delta"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">{t('alert.form.transport')}</label>
                  <select
                    name="transportType"
                    value={formData.transportType}
                    onChange={handleChange}
                    className="w-full rounded-lg border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white shadow-sm focus:border-primary focus:ring-primary py-2.5 px-3 border"
                  >
                    <option value="Tourist Boat">Tourist Boat</option>
                    <option value="Fishing Boat">Fishing Boat</option>
                    <option value="Small Wooden Boat">Small Wooden Boat</option>
                    <option value="Engine Boat">Engine Boat</option>
                    <option value="Kayak">Kayak</option>
                    <option value="Canoe">Canoe</option>
                    <option value="Motorboat">Motorboat</option>
                    <option value="Ferry">Ferry</option>
                    <option value="Walking Trail">Walking Trail</option>
                    <option value="Bicycle">Bicycle</option>
                  </select>
                </div>
              </div>

              {error && (
                <div className="p-4 bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-200 rounded-lg border border-red-200 dark:border-red-800 flex items-start gap-3">
                  <AlertTriangle className="flex-shrink-0 mt-1" size={18} />
                  <div className="flex-1">
                    <p className="text-sm font-medium flex items-center gap-2">
                       Generation Failed
                       {errorCode && <span className="text-xs bg-red-100 dark:bg-red-900/40 px-1.5 py-0.5 rounded font-mono opacity-80 border border-red-200 dark:border-red-800">{errorCode}</span>}
                    </p>
                    <p className="text-sm opacity-90 mt-1">{error}</p>
                  </div>
                  <button type="button" onClick={() => setError('')} className="text-red-500 hover:text-red-700 dark:hover:text-red-300">
                    <XCircle size={18} />
                  </button>
                </div>
              )}

              <button
                type="submit"
                disabled={loading}
                className="w-full flex justify-center items-center gap-2 py-3 px-4 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white bg-primary hover:bg-sky-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary disabled:opacity-50 transition-colors"
              >
                {loading ? t('alert.btn.generating') : t('alert.btn.gen')}
                {!loading && <Send size={18} />}
              </button>
            </form>
          </div>

          {/* Result Section */}
          {alertResult && (
            <div className="bg-slate-50 dark:bg-slate-800/50 p-8 border-t border-slate-200 dark:border-slate-800">
              <div className="flex items-start gap-4">
                <div className="bg-yellow-100 dark:bg-yellow-900/30 p-3 rounded-full text-yellow-600 dark:text-yellow-500 flex-shrink-0">
                  <AlertOctagon size={24} />
                </div>
                <div className="flex-1">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-2">{t('alert.result.title')}</h3>
                  <div className="prose dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 whitespace-pre-wrap font-sans">
                    {alertResult}
                  </div>
                  
                  <div className="mt-6 flex flex-wrap gap-3">
                     <button 
                       onClick={handleSavePDF}
                       className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition-all text-sm font-medium shadow-sm group"
                     >
                       <FileText size={16} className="text-slate-400 group-hover:text-primary"/> 
                       <span>{t('alert.save')}</span>
                     </button>
                     <button 
                       onClick={handleShare}
                       className={`flex items-center gap-2 px-4 py-2 rounded-lg border transition-all text-sm font-medium shadow-sm ${
                         copyFeedback 
                           ? 'bg-green-50 border-green-200 text-green-700 dark:bg-green-900/20 dark:border-green-800 dark:text-green-300'
                           : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700'
                       }`}
                     >
                       {copyFeedback ? <Check size={16} /> : <Share2 size={16} className={!copyFeedback ? "text-primary" : ""} />}
                       {copyFeedback ? t('alert.copied') : t('alert.share')}
                     </button>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Alerts;